### ISSUE TITLE
报错：没有叫pandas的模组

### ISSUE THREAD

**Issue by pizeroLOL** [MickLife/KeepAccounts_v2.0#2]
ModuleNotFoundError: No module named 'pandas'

**Comment by laorange** [comment]
> 
> 
> ModuleNotFoundError: No module named 'pandas'

在搜索栏搜索``cmd``来进入“命令提示符”，随后输入 ``pip install pandas``。

如果还报错就百度一下如何把python加入到环境变量里吧😁

**Comment by pizeroLOL** [comment]
> 
> 
> > ModuleNotFoundError: No module named 'pandas'
> 
> 在搜索栏搜索`cmd`来进入“命令提示符”，随后输入 `pip install pandas`。
> 
> 如果还报错就百度一下如何把python加入到环境变量里吧😁

好嘞，知道了
